// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Locomotiv.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251218043615_Initiale")]
    partial class Initiale
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("Locomotiv.Model.Block", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BlockId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstOccupe")
                        .HasColumnType("INTEGER");

                    b.Property<double>("LatitudeDebut")
                        .HasColumnType("REAL");

                    b.Property<double>("LatitudeFin")
                        .HasColumnType("REAL");

                    b.Property<double>("LongitudeDebut")
                        .HasColumnType("REAL");

                    b.Property<double>("LongitudeFin")
                        .HasColumnType("REAL");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TrainActuelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("Locomotiv.Model.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateInspection")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MecanicienId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Resultat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeInspection")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MecanicienId");

                    b.HasIndex("TrainId");

                    b.ToTable("Inspections");
                });

            modelBuilder.Entity("Locomotiv.Model.Itineraire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstActif")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StationArriveeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StationDepartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StationArriveeId");

                    b.HasIndex("StationDepartId");

                    b.HasIndex("TrainId");

                    b.ToTable("Itineraires");
                });

            modelBuilder.Entity("Locomotiv.Model.ItineraireArret", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstStation")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HeureArrivee")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HeureDepart")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItineraireId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordre")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PointInteretId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItineraireId");

                    b.HasIndex("PointInteretId");

                    b.HasIndex("StationId");

                    b.ToTable("ItineraireArrets");
                });

            modelBuilder.Entity("Locomotiv.Model.PointInteret", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PointsInteret");
                });

            modelBuilder.Entity("Locomotiv.Model.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateAnnulation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateReservation")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstActif")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItineraireId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MontantTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NombrePassagers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumeroBillet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItineraireId");

                    b.HasIndex("NumeroBillet")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("EstActif", "Statut");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Locomotiv.Model.ReservationWagon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientCommercialId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateReservation")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItineraireId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NombreWagons")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotesSpeciales")
                        .HasColumnType("TEXT");

                    b.Property<double>("PoidsTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TarifTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TypeWagon")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientCommercialId");

                    b.HasIndex("ItineraireId");

                    b.ToTable("ReservationsWagons");
                });

            modelBuilder.Entity("Locomotiv.Model.Signal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlockId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Etat")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BlockId");

                    b.HasIndex("StationId");

                    b.ToTable("Signaux");
                });

            modelBuilder.Entity("Locomotiv.Model.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CapaciteMaximale")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("Locomotiv.Model.Train", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BlockActuelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacite")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("CapaciteChargeTonnes")
                        .HasColumnType("REAL");

                    b.Property<int>("Etat")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NombreWagonsDisponibles")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NombreWagonsTotal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StationActuelleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VoieActuelleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BlockActuelId")
                        .IsUnique();

                    b.HasIndex("StationActuelleId");

                    b.HasIndex("VoieActuelleId")
                        .IsUnique();

                    b.ToTable("Trains");
                });

            modelBuilder.Entity("Locomotiv.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StationAssigneeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StationAssigneeId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Locomotiv.Model.Voie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstDisponible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TrainActuelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("Voies");
                });

            modelBuilder.Entity("Locomotiv.Model.Block", b =>
                {
                    b.HasOne("Locomotiv.Model.Block", null)
                        .WithMany("BlocksAdjacents")
                        .HasForeignKey("BlockId");
                });

            modelBuilder.Entity("Locomotiv.Model.Inspection", b =>
                {
                    b.HasOne("Locomotiv.Model.User", "Mecanicien")
                        .WithMany("InspectionsEffectuees")
                        .HasForeignKey("MecanicienId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Locomotiv.Model.Train", "Train")
                        .WithMany("Inspections")
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mecanicien");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("Locomotiv.Model.Itineraire", b =>
                {
                    b.HasOne("Locomotiv.Model.Station", "StationArrivee")
                        .WithMany()
                        .HasForeignKey("StationArriveeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Locomotiv.Model.Station", "StationDepart")
                        .WithMany()
                        .HasForeignKey("StationDepartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Locomotiv.Model.Train", "Train")
                        .WithMany()
                        .HasForeignKey("TrainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StationArrivee");

                    b.Navigation("StationDepart");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("Locomotiv.Model.ItineraireArret", b =>
                {
                    b.HasOne("Locomotiv.Model.Itineraire", "Itineraire")
                        .WithMany("Arrets")
                        .HasForeignKey("ItineraireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Locomotiv.Model.PointInteret", "PointInteret")
                        .WithMany()
                        .HasForeignKey("PointInteretId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Locomotiv.Model.Station", "Station")
                        .WithMany()
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Itineraire");

                    b.Navigation("PointInteret");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Locomotiv.Model.Reservation", b =>
                {
                    b.HasOne("Locomotiv.Model.Itineraire", "Itineraire")
                        .WithMany()
                        .HasForeignKey("ItineraireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Locomotiv.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Itineraire");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Locomotiv.Model.ReservationWagon", b =>
                {
                    b.HasOne("Locomotiv.Model.User", "ClientCommercial")
                        .WithMany()
                        .HasForeignKey("ClientCommercialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Locomotiv.Model.Itineraire", "Itineraire")
                        .WithMany()
                        .HasForeignKey("ItineraireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientCommercial");

                    b.Navigation("Itineraire");
                });

            modelBuilder.Entity("Locomotiv.Model.Signal", b =>
                {
                    b.HasOne("Locomotiv.Model.Block", "Block")
                        .WithMany("Signaux")
                        .HasForeignKey("BlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Locomotiv.Model.Station", "Station")
                        .WithMany("Signaux")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Block");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Locomotiv.Model.Train", b =>
                {
                    b.HasOne("Locomotiv.Model.Block", "BlockActuel")
                        .WithOne("TrainActuel")
                        .HasForeignKey("Locomotiv.Model.Train", "BlockActuelId");

                    b.HasOne("Locomotiv.Model.Station", "StationActuelle")
                        .WithMany("TrainsEnGare")
                        .HasForeignKey("StationActuelleId");

                    b.HasOne("Locomotiv.Model.Voie", "VoieActuelle")
                        .WithOne("TrainActuel")
                        .HasForeignKey("Locomotiv.Model.Train", "VoieActuelleId");

                    b.Navigation("BlockActuel");

                    b.Navigation("StationActuelle");

                    b.Navigation("VoieActuelle");
                });

            modelBuilder.Entity("Locomotiv.Model.User", b =>
                {
                    b.HasOne("Locomotiv.Model.Station", "StationAssignee")
                        .WithMany("EmployesAssignes")
                        .HasForeignKey("StationAssigneeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StationAssignee");
                });

            modelBuilder.Entity("Locomotiv.Model.Voie", b =>
                {
                    b.HasOne("Locomotiv.Model.Station", "Station")
                        .WithMany("Voies")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Locomotiv.Model.Block", b =>
                {
                    b.Navigation("BlocksAdjacents");

                    b.Navigation("Signaux");

                    b.Navigation("TrainActuel");
                });

            modelBuilder.Entity("Locomotiv.Model.Itineraire", b =>
                {
                    b.Navigation("Arrets");
                });

            modelBuilder.Entity("Locomotiv.Model.Station", b =>
                {
                    b.Navigation("EmployesAssignes");

                    b.Navigation("Signaux");

                    b.Navigation("TrainsEnGare");

                    b.Navigation("Voies");
                });

            modelBuilder.Entity("Locomotiv.Model.Train", b =>
                {
                    b.Navigation("Inspections");
                });

            modelBuilder.Entity("Locomotiv.Model.User", b =>
                {
                    b.Navigation("InspectionsEffectuees");
                });

            modelBuilder.Entity("Locomotiv.Model.Voie", b =>
                {
                    b.Navigation("TrainActuel")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
